### ISSUE TITLE
nil included in RESULTS

### ISSUE THREAD

**Issue by devn** [stardiviner/ob-clojure-literate#3]
Emacs: `GNU Emacs 25.3.1`
cider: `cider-20180509.109`
org: running from source as of the date of this posting
ob-clojure-literate: running from source as of the date of this posting

relevant config:
```
(add-to-list 'load-path "/Users/myuser/.emacs.d/elisp/org-mode/lisp/")
(add-to-list 'load-path "/Users/myuser/.emacs.d/elisp/org-mode/contrib/lisp/")
(require 'org)
(require 'ob-clojure-literate)
(setq ob-clojure-literate-auto-jackin-p t)
(add-hook 'org-mode-hook #'ob-clojure-literate-mode)
```

Example:
```
#+begin_src clojure :results value
(+ 1 4)
#+end_src

#+RESULTS:
: nil5
```

I would expect this to simply be `5`.

Another example with multiple forms:
```
#+BEGIN_SRC clojure :results value
  (ns foo)
  (def x 1)
  (inc x)
#+END_SRC

#+RESULTS:
: nilnil#'foo/x2
```

**Comment by stardiviner** [comment]
Have you tried without loading `ob-clojure-literate`, because it seems from `ob-clojure`. Actually `ob-clojure-literature` will not manipulate on the cider/nrepl result.

**Comment by stardiviner** [comment]
@devn Hi, have any update on this issue? If not, I close it now.
